### PR TITLE
Added Travis CI support.

### LINKED ISSUE #12: Using git-cop with Travis
From the readme

> Calculation of commits is done by reviewing all commits made on the current feature branch since branching from master. Some CI servers don't respect this and blow away any branch information, most notibly, Travis CI. For that reason, Travis CI is not supported or recommended as they use git clone --depth=<number> cloning which can't be customized and destroys any knowledge of master and feature branch information.

Does that mean that git-cop can not be used in Travis?

### PR DESCRIPTION
**Pull request by bkuhlmann**
## Overview

Provides Travis CI build support which means anyone can use this gem to check builds on the following tested build servers:

- Circle CI
- Travis CI

## Details

- Resolves #12.
- This work is based off of @Ana06's original work found in this [pull request](https://github.com/bkuhlmann/git-cop/pull/16). Thanks @Ana06!
- An example Travis CI build with Git Cop executing properly can be found [here](https://travis-ci.org/bkuhlmann/git-cop/builds/251806818).

### CODE REVIEW

**Comment by bkuhlmann** [comment]
:information_source: Ignoring the `continuous-integration/travis-ci/pr` check for now. This is a second build by Travis CI where it attempts to build with the feature branch rebased on master. Not actually interested in this build for the moment, might address later, though.

**Comment by Ana06** [comment]
@bkuhlmann would have been nice if you had cherry-pick my commit. Because I found out how to support Travis, but now only your name is in the commits. :unamused:

**Comment by bkuhlmann** [comment]
Yeah, sorry about that, it's been bugging me too. I did want to find a way to give you attribution but after spending time refactoring the code and adding missing specs, the end result was quite different.

That said, there is a case to be made for allowing the code to be merged and refactored afterwards. I've gotten used to using a very strict Git rebase workflow that works hard to keep the Git history as clean as possible (i.e. make the implementation and corresponding spec that is committed be the most polished and production-ready version -- that's the goal anyway, doesn't always happen). In this case, the PR could have been merged and refactored. I was using my weekend to get as much of this work done and tested for a `1.2.0` release but that doesn't excuse the fact that I wasn't able to give better attribution to you. I apologize for this.

Moving forward I will work to be more cognizance of this. I will make sure to mention co-authors in the Git commits themselves. I'm also working on a [Milestoner](https://github.com/bkuhlmann/milestoner) feature which will add author attribution to the release notes as well so the `CHANGES.md` file gives author attribution.

**Comment by Ana06** [comment]
@bkuhlmann 
>  I did want to find a way to give you attribution but after spending time refactoring the code and adding missing specs, the end result was quite different.

The result is quite different but the idea is mine. If you refactor a code that is mine, you should either:

1. cherrypick my commit and afterwards modify it so it is clear who is author of what
2. if you want the Git history as clean as possible, you can also change the author of your commit and adding myself as author.

and you can still do any of both things even if the PR is merged.

I really appreciate that you work that fast to have this in the gem that fast, but I feel disappointed that I worked on something and at the end my name is not there. :disappointed:

**Comment by bkuhlmann** [comment]
I agree, you are the author of the solution in it's original form. Both of your suggestions would apply attribution to you. What you are suggesting, unfortunately, is to rewrite history of the `master` branch. That would invalidate any downstream forks (granted, your fork is the only known fork at this time), void all signed and released tags of this project, and be a general breach of contract to anyone who might have cloned the project in some undetected form.

What I have done is attributed you in this PR and well as thanked you for your original solution. I am also happy to give credit to you if anyone asks about the original support in the future. I can also provide written credit and recommendation if you need it for anyone asking about Travis CI support related to your work here.

Regarding Rubocop, yeah I'm planning to do something similar with Milestoner so the process is entirely automated.

**Comment by Ana06** [comment]
@bkuhlmann just in case something like this happens again in the future. The new [_Commit together with co-authors_ Github feature](https://github.com/blog/2496-commit-together-with-co-authors) allow easily to give attribution to more people in you commits. Just to let you know 😉

**Comment by bkuhlmann** [comment]
Thanks! Yep, been thinking about how to incorporate this in a manner that is not too cumbersome.

**Pull request merged**
