### PR TITLE
Fixed typo in default configuration of README.md.

### PR DESCRIPTION
**Pull request by mimadrid**
Fixed error message:

Invalid configuration (/home/user/.config/git-cop/configuration.yml): could not find expected ':' while scanning a simple key at line 46 column 3.

### CODE REVIEW

**Comment by mimadrid** [comment]
Hi @Ana06, thanks for reviewing the pull request

I also have a question with the next message from my config:
>  Body Leading Space Warning. Deprecated. Use Commit Body Leading Line instead.

because of:
> :commit_body_leading_line:
>   :enabled: false
>   :severity: :warn
> :commit_body_leading_space:
>   :enabled: true
>   :severity: :error

Which are the best enabled and severity options here for updating the README file?

Cheers

**Comment by Ana06** [comment]
@mimadrid `:commit_body_leading_space:` is deprecated. Now it is `:commit_body_leading_space:`.  I guess we should remove it from the README. @bkuhlmann can we remove it or is it there on propose?

**Comment by bkuhlmann** [comment]
@mimadrid Thanks for catching and fixing that typo!

@Ana06 No problem, I'll work on that this weekend. It's actually a good thing that it breaks like this. It helps us know when to upgrade to the latest Rubocop changes. Otherwise, it becomes a nightmare to maintain.

@mimadrid, @Ana06 Regarding the deprecation warning from the README. I agree, it needs to be removed. We can do it now or wait until the 2.0.0 release (at the turn of the year) where support for that feature will be removed entirely.

:bulb: In the future, remember that you can `[ci skip]` to the body of your commit messages in order to skip CI builds for documentation changes. That's perfectly fine to do as there is nothing to build anyway.

:white_check_mark: I'll rebased this onto `master`. Thanks again.

**Comment by Ana06** [comment]
@bkuhlmann 

>@Ana06 No problem, I'll work on that this weekend. It's actually a good thing that it breaks like this. It helps us know when to upgrade to the latest Rubocop changes. Otherwise, it becomes a nightmare to maintain.

What about using [depfu](https://depfu.com/how-it-works) to update gems instead breaking the test suite?

**Comment by bkuhlmann** [comment]
Thanks. I'll look into that. Been using [Gemnasium](https://gemnasium.com) for weekly updates. The problem is that some dependencies can't be fully automated. In the case of linters, like Rubocop, it generally requires manual changes to the source code...but I'll check it out.

**Comment by Ana06** [comment]
Yes, normally you will need to update the PR to include the source code changes but I find it better than waiting to the test suite to fail 😉

**Pull request merged**
