### PR TITLE
Fixed default configuration in README.

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
## Overview

The default configuration in README was not valid. I was getting 

```
Invalid configuration (/path/to/configuration.yml): did not find expected '-' indicator while parsing a block collection at line 47 column 5.
```

when using it.

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
CI failed because of a rubocop upgrade. It sounds that you should either commit `Gemfile.lock`, or tighten the development dependency.

**Comment by bkuhlmann** [comment]
:bow: Thanks for catching this. It's [happened before](https://github.com/bkuhlmann/git-cop/commit/7c64373309d7cee90b9e044098ea4c762cb7dc9c), unfortunately. It's easy to miss when updating the documentation. Yeah, build is failing due to the new Rubocop release. I'll fix and then you can rebase upon master to get this build green. Will post an update shortlyl

**Comment by bkuhlmann** [comment]
:information_source: If you rebase from latest changes on `master`, this build will go green.

**Comment by bkuhlmann** [comment]
Thanks. Yeah, I've read those articles before (well, at least Bundler's). It's a bit more complicated than it seems. As a gem maintainer, you'd almost have to update a project on a weekly basis (maybe sooner or as updates are released for immediate turn around time). The problem with this is that there is a lot of churn on the `Gemfile.lock` that seems a unnecessary (it also leads to a noisy Git history).

The other issue is with Rubocop. If they obeyed semantic versioning and had more regulated releases, this wouldn't be as big of an issue for all of us downstream. Every release of Rubocop is almost always a breaking change, unfortunately.

That said, I've been thinking about this more. It will add more maintenance cost for me across all projects, but yes, could improve in the contributor experience.

**Comment by deivid-rodriguez** [comment]
Rebased! :smiley:

**Comment by bkuhlmann** [comment]
> I think it all comes down to what each of us considers as "noise".

Fair enough.

> Well, technically rubocop follows semantic versioning since they are still 0.x.

I guess I'm grumbling mostly because after ~59 (actually more) releases, they still haven't settled on a 1.0.0 which seem a bit long in the tooth.

>  its [bot] commit messages won't match git-cop's restrictions.

True, I've not seen a bot that fully customizable yet.

:white_check_mark: Thanks for rebasing!

**Comment by deivid-rodriguez** [comment]
Thanks to you for merging and for your cool libraries! :muscle:

**Pull request merged**
