### PR TITLE
Address RuboCop offences

### PR DESCRIPTION
**Pull request by koenrh**
This address the RuboCop offences introduce in a recent update.

Offences in the Gem specification file could be autocorrected.

The one offence in `base.rb` seems to be a bug in RuboCop where it incorrectly confuses string interpolation with a code comment. I have address the issue for now by disabling the particular cop, but we could also update the constructor to pass `message || "[error message]"` to `super`.

```
lib/git/cop/errors/base.rb:8:43: C: Style/CommentedKeyword: Do not place comments on the same line as the def keyword.
        def initialize message = "Invalid #{Identity.label} action."
```

### CODE REVIEW

**Comment by bkuhlmann** [comment]
Thanks, yeah, I ran into that issue as well with the new Rubocop update. It *is* a bug with Rubocop, unfortunately. I might end up fixing this is a different way as I'm working on the same Rubocop cop update to all my open source projects at the same time (it's easier, for me at least, to do the update across them all at once).

I'm currently traveling at the moment, and don't have the best connectivity. I'll be a little slow responding until this weekend. More news soon!

**Comment by bkuhlmann** [comment]
:information_source: Closing this PR as it's been fixed in master with this [commit](https://github.com/bkuhlmann/git-cop/commit/7b7360ffd41c48cbb53c82fe77667b8846f6ffbb). Sorry to ignore your work on this but it was easier to apply the same commit to all my open source projects at once (which included this project).

**Comment by Ana06** [comment]
@bkuhlmann 

> Closing this PR as it's been fixed in master with this commit. Sorry to ignore your work on this but it was easier to apply the same commit to all my open source projects at once (which included this project).

Easier than pressing merge? :unamused: This is exactly the same change as in your commit. I think it would have been nice to recognise @koenrh work by allowing that his name is in the commit.

**Comment by bkuhlmann** [comment]
@Ana06 Please read the above discussion. I apologized and acknowledged his work in this PR. None of this was of significant effort. I was also traveling and didn't have the best internet connectivity last week. Truth be told, I had the issue resolved shortly after it was identified but it took me several days to apply my changes (keep in mind that I maintain several projects, so the update applied to all of the projects I maintain is more obscured when looking at commit activity at this single project level).

This is more of a case of two ships in the night passing by each other, doing the same thing. :)

**Pull request closed without merging**
